### ISSUE TITLE
error  when running

### ISSUE THREAD

**Issue by typonino** [svent/jsdetox#21]
Hello,

I have installed jsdetox within my rvm env and get error at runtime
list of used dependencies:
Using rake 11.1.2
Using i18n 0.7.0
Using multi_json 1.11.3
Using haml 3.1.8
Using hexdump 0.2.3
Using rack 1.6.4
Using json 1.8.3
Using libv8 3.3.10.4
Using mime-types 1.25.1
Using polyglot 0.3.5
Using mini_portile2 2.0.0
Using tilt 1.3.7
Using thor 0.15.4
Using bundler 1.12.0
Using sass 3.4.22
Using activesupport 3.2.22.2
Using url_mount 0.2.1
Using rack-protection 1.5.3
Using therubyracer 0.9.8
Using treetop 1.4.15
Using nokogiri 1.6.7.2
Using http_router 0.10.2
Using sinatra 1.3.6
Using mail 2.3.3
Using padrino-core 0.10.7
Using padrino-helpers 0.10.7
Using padrino-cache 0.10.7
Using padrino-gen 0.10.7
Using padrino-mailer 0.10.7
Using padrino-admin 0.10.7
Using padrino 0.10.7

Error message:

> [JSDetox] Loading framework ... done.
> [JSDetox] Starting webserver (hit Ctrl-C to quit) ...
> => Padrino/0.10.7 has taken the stage development at http://192.168.254.3:3000
> [2016-04-29 11:52:17] INFO  WEBrick 1.3.1
> [2016-04-29 11:52:17] INFO  ruby 2.3.0 (2015-12-25) [x86_64-linux]
> [2016-04-29 11:52:17] INFO  WEBrick::HTTPServer#start: pid=23131 port=3000
> Thread.exclusive is deprecated, use Mutex
> /home/emailanalyzer/.rvm/gems/ruby-2.3.0/gems/padrino-core-0.10.7/lib/padrino-core/reloader.rb:247:in `call'
> /home/emailanalyzer/.rvm/gems/ruby-2.3.0/gems/padrino-core-0.10.7/lib/padrino-core/logger.rb:388:in`call'
> /home/emailanalyzer/.rvm/gems/ruby-2.3.0/gems/sinatra-1.3.6/lib/sinatra/showexceptions.rb:21:in `call'
> /home/emailanalyzer/.rvm/gems/ruby-2.3.0/gems/sinatra-1.3.6/lib/sinatra/base.rb:1417:in`block in call'
> /home/emailanalyzer/.rvm/gems/ruby-2.3.0/gems/sinatra-1.3.6/lib/sinatra/base.rb:1499:in `synchronize'
> /home/emailanalyzer/.rvm/gems/ruby-2.3.0/gems/sinatra-1.3.6/lib/sinatra/base.rb:1417:in`call'
> /home/emailanalyzer/.rvm/gems/ruby-2.3.0/gems/padrino-core-0.10.7/lib/padrino-core/router.rb:83:in `block in call'
> /home/emailanalyzer/.rvm/gems/ruby-2.3.0/gems/padrino-core-0.10.7/lib/padrino-core/router.rb:76:in`each'
> /home/emailanalyzer/.rvm/gems/ruby-2.3.0/gems/padrino-core-0.10.7/lib/padrino-core/router.rb:76:in `call'
> /home/emailanalyzer/.rvm/gems/ruby-2.3.0/gems/rack-1.6.4/lib/rack/handler/webrick.rb:88:in`service'
> /home/emailanalyzer/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/webrick/httpserver.rb:140:in `service'
> /home/emailanalyzer/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/webrick/httpserver.rb:96:in`run'
> /home/emailanalyzer/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/webrick/server.rb:296:in `block in start_thread'
> [2016-04-29 11:52:27] ERROR NoMethodError: undefined method`join' for #String:0x000000040f5420
>         /home/emailanalyzer/.rvm/gems/ruby-2.3.0/gems/sinatra-1.3.6/lib/sinatra/showexceptions.rb:37:in `rescue in call'
>         /home/emailanalyzer/.rvm/gems/ruby-2.3.0/gems/sinatra-1.3.6/lib/sinatra/showexceptions.rb:21:in`call'
>         /home/emailanalyzer/.rvm/gems/ruby-2.3.0/gems/sinatra-1.3.6/lib/sinatra/base.rb:1417:in `block in call'
>         /home/emailanalyzer/.rvm/gems/ruby-2.3.0/gems/sinatra-1.3.6/lib/sinatra/base.rb:1499:in`synchronize'
>         /home/emailanalyzer/.rvm/gems/ruby-2.3.0/gems/sinatra-1.3.6/lib/sinatra/base.rb:1417:in `call'
>         /home/emailanalyzer/.rvm/gems/ruby-2.3.0/gems/padrino-core-0.10.7/lib/padrino-core/router.rb:83:in`block in call'
>         /home/emailanalyzer/.rvm/gems/ruby-2.3.0/gems/padrino-core-0.10.7/lib/padrino-core/router.rb:76:in `each'
>         /home/emailanalyzer/.rvm/gems/ruby-2.3.0/gems/padrino-core-0.10.7/lib/padrino-core/router.rb:76:in`call'
>         /home/emailanalyzer/.rvm/gems/ruby-2.3.0/gems/rack-1.6.4/lib/rack/handler/webrick.rb:88:in `service'
>         /home/emailanalyzer/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/webrick/httpserver.rb:140:in`service'
>         /home/emailanalyzer/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/webrick/httpserver.rb:96:in `run'
>         /home/emailanalyzer/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/webrick/server.rb:296:in`block in start_thread'

Any help on that issue would be appreciate !

Regards,

**Comment by svent** [comment]
Unfortunately, dependencies are quite an issues due to required versions of some libraries. You could try to use JSDetox with a ruby 2.1 setup instead of 2.3, but I am not sure if that will help.
By now, JSDetox is best run in a virtual machine with Ubuntu 14.04 LTS or using the docker image provided by Lenny Zeltser (see [here](https://zeltser.com/docker-application-distribution/)): `docker run --rm -p 3000:3000 remnux/jsdetox`
