### ISSUE TITLE
Fresh installation with 500 error: undefined method `join' for #&lt;String:0x00000003d148d8&gt;

### ISSUE THREAD

**Issue by CaledoniaProject** [svent/jsdetox#25]
Take a look please?

```
[JSDetox] Loading framework ... done.
[JSDetox] Starting webserver (hit Ctrl-C to quit) ...
=> Padrino/0.10.7 has taken the stage development at http://127.0.0.1:3000
[2017-06-29 15:10:09] INFO  WEBrick 1.3.1
[2017-06-29 15:10:09] INFO  ruby 2.3.1 (2016-04-26) [x86_64-linux-gnu]
[2017-06-29 15:10:09] INFO  WEBrick::HTTPServer#start: pid=58596 port=3000
Thread.exclusive is deprecated, use Mutex
/var/lib/gems/2.3.0/gems/padrino-core-0.10.7/lib/padrino-core/reloader.rb:247:in `call'
/var/lib/gems/2.3.0/gems/padrino-core-0.10.7/lib/padrino-core/logger.rb:388:in `call'
/var/lib/gems/2.3.0/gems/sinatra-1.3.6/lib/sinatra/showexceptions.rb:21:in `call'
/var/lib/gems/2.3.0/gems/sinatra-1.3.6/lib/sinatra/base.rb:1417:in `block in call'
/var/lib/gems/2.3.0/gems/sinatra-1.3.6/lib/sinatra/base.rb:1499:in `synchronize'
/var/lib/gems/2.3.0/gems/sinatra-1.3.6/lib/sinatra/base.rb:1417:in `call'
/var/lib/gems/2.3.0/gems/padrino-core-0.10.7/lib/padrino-core/router.rb:83:in `block in call'
/var/lib/gems/2.3.0/gems/padrino-core-0.10.7/lib/padrino-core/router.rb:76:in `each'
/var/lib/gems/2.3.0/gems/padrino-core-0.10.7/lib/padrino-core/router.rb:76:in `call'
/var/lib/gems/2.3.0/gems/rack-1.6.8/lib/rack/handler/webrick.rb:88:in `service'
/usr/lib/ruby/2.3.0/webrick/httpserver.rb:140:in `service'
/usr/lib/ruby/2.3.0/webrick/httpserver.rb:96:in `run'
/usr/lib/ruby/2.3.0/webrick/server.rb:296:in `block in start_thread'
[2017-06-29 15:10:10] ERROR NoMethodError: undefined method `join' for #<String:0x00000003d148d8>
	/var/lib/gems/2.3.0/gems/sinatra-1.3.6/lib/sinatra/showexceptions.rb:37:in `rescue in call'
	/var/lib/gems/2.3.0/gems/sinatra-1.3.6/lib/sinatra/showexceptions.rb:21:in `call'
	/var/lib/gems/2.3.0/gems/sinatra-1.3.6/lib/sinatra/base.rb:1417:in `block in call'
	/var/lib/gems/2.3.0/gems/sinatra-1.3.6/lib/sinatra/base.rb:1499:in `synchronize'
	/var/lib/gems/2.3.0/gems/sinatra-1.3.6/lib/sinatra/base.rb:1417:in `call'
	/var/lib/gems/2.3.0/gems/padrino-core-0.10.7/lib/padrino-core/router.rb:83:in `block in call'
	/var/lib/gems/2.3.0/gems/padrino-core-0.10.7/lib/padrino-core/router.rb:76:in `each'
	/var/lib/gems/2.3.0/gems/padrino-core-0.10.7/lib/padrino-core/router.rb:76:in `call'
	/var/lib/gems/2.3.0/gems/rack-1.6.8/lib/rack/handler/webrick.rb:88:in `service'
	/usr/lib/ruby/2.3.0/webrick/httpserver.rb:140:in `service'
	/usr/lib/ruby/2.3.0/webrick/httpserver.rb:96:in `run'
	/usr/lib/ruby/2.3.0/webrick/server.rb:296:in `block in start_thread'
```

```
# curl 127.0.0.1:3000
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN">
<HTML>
  <HEAD><TITLE>Internal Server Error</TITLE></HEAD>
  <BODY>
    <H1>Internal Server Error</H1>
    undefined method `join' for #&lt;String:0x00000003d148d8&gt;
    <HR>
    <ADDRESS>
     WEBrick/1.3.1 (Ruby/2.3.1/2016-04-26) at
     127.0.0.1:3000
    </ADDRESS>
  </BODY>
</HTML>
```

**Comment by LiYouliang** [comment]
I get the same error. And I found the the comments on https://github.com/sinatra/sinatra/issues/951#issuecomment-84572703, the error could be fixed by update sinatra. But when I try to do so, there are still have other dependencies problem:

```
Bundler could not find compatible versions for gem "sinatra":
  In Gemfile:
    padrino (~> 0.10.5) was resolved to 0.10.5, which depends on
      padrino-core (= 0.10.5) was resolved to 0.10.5, which depends on
        sinatra (~> 1.3.1)

    sinatra-fix_951 was resolved to 1.0.0, which depends on
      sinatra (= 1.4.5)
```
